### ISSUE TITLE
MobApp: Missing attribution for OpenStreetMap

### ISSUE THREAD

**Issue by pietervdvn** [oSoc18/gentlestudent#106]
When using OpenStreetMap, giving a small attribution is obligated. When using Mapbox, they require attribution as well.

Preferably, the copyright notice would be shown on the map itself, but giving attributions on some info page is fine as well.

**Comment by mrvdries** [comment]
Added attribution to the map in lower right corner.

**Comment by pietervdvn** [comment]
Superb, thx!

On Jul 30, 2018 17:35, "Maxime Van Driessche" <notifications@github.com>
wrote:

Added attribution to the map in lower right corner.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/oSoc18/gentlestudent/issues/106#issuecomment-408906921>,
or mute the thread
